---
- name: Common role for all server
  become: true
  hosts: all
  roles:
    - initial

- name: Install etcd
  become: true
  hosts: controllers
  roles:
    - etcd

- name: Kuber-config
  become: true
  hosts: controllers
  roles:
    - kuber-config
