---
- name: Setting hostname
  hostname:
    name: "{{ hostname_name }}"
  when: hostname_name is defined

- name: Copy etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Copy tools
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    owner: root
    mode: 0755
  with_fileglob:
    - files/cfssl
    - files/cfssljson
    - files/kubectl

- name: Distribute Certificates to workers
  copy:
    src: "{{ item }}"
    dest: /root/
    owner: root
    mode: 0644
  with_fileglob:
    - files/certs/ca.pem
    - "files/certs/{{ hostname_name }}-key.pem"
    - "files/certs/{{ hostname_name }}.pem"
    - "files/configs/{{ hostname_name }}.kubeconfig"
    - files/configs/kube-proxy.kubeconfig
  when: "'workers' in group_names"

- name: Distribute Certificates to controllers
  copy:
    src: "{{ item }}"
    dest: /root/
    owner: root
    mode: 0644
  with_fileglob:
    - files/certs/ca.pem
    - files/certs/ca-key.pem
    - files/certs/kubernetes.pem
    - files/certs/kubernetes-key.pem
    - files/certs/service-account.pem
    - files/certs/service-account-key.pem
    - files/configs/admin.kubeconfig
    - files/configs/kube-controller-manager.kubeconfig
    - files/configs/kube-scheduler.kubeconfig
  when: "'controllers' in group_names"
