- name: Copy etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Setting hostname
  hostname:
    name: "{{ hostname_name }}"
  when: hostname_name is defined

- name: Controllers tasks
  include_tasks: controllers.yml
  when: "'controllers' in group_names"

- name: Workers tasks
  include_tasks: workers.yml
  when: "'workers' in group_names"
