---
- name: Install supp packages
  apt:
    name:
      - socat
      - conntrack
      - ipset
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Make dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0644
  with_items:
    - /opt/cni
    - /etc/cni/net.d
    - /opt/cni/bin
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /var/lib/kubernetes
    - /var/run/kubernetes
    - /etc/containerd

- name: Copy certs to /var/lib/kubelet
  copy:
    src: "{{ item }}"
    dest: /var/lib/kubelet
    owner: root
    mode: 0644
  with_fileglob:
    - "files/certs/{{ hostname_name }}.pem"
    - "files/certs/{{ hostname_name }}-key.pem"

- name: Copy kube-proxy.config
  copy:
    src: files/configs/kube-proxy.kubeconfig
    dest: /var/lib/kube-proxy/kubeconfig
    owner: root
    mode: 0644

- name: Copy certs to /var/lib/kubelet
  copy:
    src: "files/configs/{{ hostname_name }}.kubeconfig"
    dest: /var/lib/kubelet/kubeconfig
    owner: root
    mode: 0644

- name: Copy ca.pem to /var/lib/kubernetes
  copy:
    src: files/certs/ca.pem
    dest: /var/lib/kubernetes
    owner: root
    mode: 0644

- name: Copy tools to /usr/local/bin
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    owner: root
    mode: 0755
  with_fileglob:
    - files/tools/kubectl
    - files/tools/kube-proxy
    - files/tools/kubelet
    - files/tools/runc
    - files/tools/runsc
    - files/tools/crictl

- name: Copy tools to /bin
  copy:
    src: "{{ item }}"
    dest: /bin
    owner: root
    mode: 0755
  with_fileglob:
    - files/tools/bin/containerd
    - files/tools/bin/containerd-shim
    - files/tools/bin/containerd-shim-runc-v1
    - files/tools/bin/containerd-stress
    - files/tools/bin/ctr

- name: Copy tools to /opt/cni/bin
  copy:
    src: "{{ item }}"
    dest: /opt/cni/bin
    owner: root
    mode: 0755
  with_fileglob:
    - files/tools/crictl
    - files/tools/bridge
    - files/tools/dhcp
    - files/tools/flannel
    - files/tools/host-device
    - files/tools/host-local
    - files/tools/ipvlan
    - files/tools/loopback
    - files/tools/macvlan
    - files/tools/portmap
    - files/tools/ptp
    - files/tools/sample
    - files/tools/tuning
    - files/tools/vlan

- name: Bridge template
  template:
    src: bridge.conf.j2
    dest: /etc/cni/net.d/10-bridge.conf
  
- name: Loopback template
  template:
    src: loopback.conf.j2
    dest: /etc/cni/net.d/99-loopback.conf

- name: Containerd config template
  template:
    src: containerd-config.toml.j2
    dest: /etc/containerd/config.toml
