---
- name: kube-controller-manager-systemd-reload
  systemd:
    enabled: true
    daemon_reload: true
    name: kube-controller-manager
    state: restarted

- name: kube-apiserver-systemd-reload
  systemd:
    enabled: true
    daemon_reload: true
    name: kube-apiserver
    state: restarted

- name: kube-scheduler-reload
  systemd:
    enabled: true
    daemon_reload: true
    name: kube-scheduler
    state: restarted

- name: containerd-reload
  systemd:
    enabled: true
    daemon_reload: true
    name: containerd
    state: restarted

- name: kubelet-reload
  systemd:
    enabled: true
    daemon_reload: true
    name: kubelet
    state: restarted

- name: kube-proxy-reload
  systemd:
    enabled: true
    daemon_reload: true
    name: kube-proxy
    state: restarted
